// Codex adapter — spawns OpenAI Codex CL
import { BaseAdapter } from "../base";
import { Agent, AdapterEnvironmentTestResult, AdapterConfig } from "@nmj/shared/types";
export class CodexAdapter extends BaseAdapter {  type = "codex";
  label = "Codex";
  description = "OpenAI Codex CLI — stateless coding agent";
  async isAvailable(agent: Agent): Promise<boolean> {    const config = this.parseConfig(agent);
    const command = config.command || "codex";
    return this.checkCommandExists(command);
  }  async execute(agent: Agent, message: string, context?: string): Promise<string> {    const config = this.parseConfig(agent);
    const command = config.command || "codex";
    const cwd = config.cwd || process.cwd();
    const model = config.model || "gpt-5.3-codex";
    const timeoutSec = config.timeoutSec || 600;
    const args = ["exec"];
    if (model) args.push("-c", `model=${model}`);
    if (config.modelReasoningEffort) {      args.push("-c", `model_reasoning_effort=${config.modelReasoningEffort}`);
    }    if (config.search) args.push("--search");
    if (config.fastMode) args.push("--fast");
    if (config.dangerouslyBypassSandbox !== false) {      args.push("--dangerously-bypass-approvals-and-sandbox");
    }    const env = this.buildEnv(agent, config, {      OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",    });
    const fullPrompt = context      ? `[Context]\n${context}\n\n[Task]\n${message}`      : message;
    const result = await this.runCommand(command, [...args, fullPrompt], {      cwd,      env,      timeoutSec,      graceSec: config.graceSec || 20,    });
    if (result.timedOut) {      throw new Error(`Codex timed out after ${timeoutSec}s`);
    }    if (result.exitCode !== 0) {      throw new Error(`Codex exited with code ${result.exitCode}: ${result.stderr}`);
    }    return result.stdout.trim();
  }  async executeStreaming(    agent: Agent,    message: string,    context: string | undefined,    onChunk: (chunk: string) => void  ): Promise<string> {    const config = this.parseConfig(agent);
    const command = config.command || "codex";
    const cwd = config.cwd || process.cwd();
    const model = config.model || "gpt-5.3-codex";
    const timeoutSec = config.timeoutSec || 600;
    const args = ["exec"];
    if (model) args.push("-c", `model=${model}`);
    if (config.modelReasoningEffort) {      args.push("-c", `model_reasoning_effort=${config.modelReasoningEffort}`);
    }    if (config.search) args.push("--search");
    if (config.fastMode) args.push("--fast");
    if (config.dangerouslyBypassSandbox !== false) {      args.push("--dangerously-bypass-approvals-and-sandbox");
    }    const env = this.buildEnv(agent, config, {      OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",    });
    const fullPrompt = context      ? `[Context]\n${context}\n\n[Task]\n${message}`      : message;    let fullText = "";
    const result = await this.runCommand(command, [...args, fullPrompt], {      cwd,      env,      timeoutSec,      graceSec: config.graceSec || 20,      onStdout: (data) => {        fullText += data;
        onChunk(data);
      },    });
    if (result.timedOut) {      throw new Error(`Codex timed out after ${timeoutSec}s`);
    }    if (result.exitCode !== 0 && !fullText) {      throw new Error(`Codex exited with code ${result.exitCode}: ${result.stderr}`);
    }    return fullText;
  }  async testEnvironment(agent: Agent): Promise<AdapterEnvironmentTestResult> {    const checks: any[] = [];
    const config = this.parseConfig(agent);
    const command = config.command || "codex";
    const cliExists = await this.checkCommandExists(command);    checks.push({      code: "cli_exists",      level: cliExists ? "info" : "error",      message: cliExists        ? `Codex CLI found: ${command}`        : `Codex CLI not found: ${command}`,      hint: cliExists ? null : "Install with: npm install -g @openai/codex",    });
    if (!cliExists) {      return this.createTestResult(this.type, "fail", checks);
    }    const hasApiKey = !!process.env.OPENAI_API_KEY;    checks.push({      code: "auth",      level: hasApiKey ? "info" : "error",      message: hasApiKey        ? "OPENAI_API_KEY is set"        : "OPENAI_API_KEY is not set",      hint: hasApiKey ? null : "Set OPENAI_API_KEY environment variable",    });
    if (config.model) {      checks.push({        code: "model",        level: "info",        message: `Model: ${config.model}`,      });
    }    const hasError = checks.some((c) => c.level === "error");
    return this.createTestResult(this.type, hasError ? "fail" : "pass", checks);
  }}