// Cursor adapter — spawns Cursor agent in background mod
import { BaseAdapter } from "../base";
import { Agent, AdapterEnvironmentTestResult, AdapterConfig } from "@nmj/shared/types";
export class CursorAdapter extends BaseAdapter {  type = "cursor";
  label = "Cursor";
  description = "Cursor IDE agent — runs in background mode";
  async isAvailable(agent: Agent): Promise<boolean> {    const config = this.parseConfig(agent);
    const command = config.command || "agent";
    return this.checkCommandExists(command);
  }  async execute(agent: Agent, message: string, context?: string): Promise<string> {    const config = this.parseConfig(agent);
    const command = config.command || "agent";
    const cwd = config.cwd || process.cwd();
    const model = config.model || "";
    const timeoutSec = config.timeoutSec || 600;
    const args = ["--background"];
    if (model) args.push("--model", model);
    const env = this.buildEnv(agent, config);
    const fullPrompt = context      ? `[Context]\n${context}\n\n[Task]\n${message}`      : message;
    const result = await this.runCommand(command, [...args, fullPrompt], {      cwd,      env,      timeoutSec,      graceSec: config.graceSec || 20,    });
    if (result.timedOut) {      throw new Error(`Cursor timed out after ${timeoutSec}s`);
    }    if (result.exitCode !== 0) {      throw new Error(`Cursor exited with code ${result.exitCode}: ${result.stderr}`);
    }    return result.stdout.trim();
  }  async executeStreaming(    agent: Agent,    message: string,    context: string | undefined,    onChunk: (chunk: string) => void  ): Promise<string> {    const config = this.parseConfig(agent);
    const command = config.command || "agent";
    const cwd = config.cwd || process.cwd();
    const model = config.model || "";
    const timeoutSec = config.timeoutSec || 600;
    const args = ["--background"];
    if (model) args.push("--model", model);
    const env = this.buildEnv(agent, config);
    const fullPrompt = context      ? `[Context]\n${context}\n\n[Task]\n${message}`      : message;    let fullText = "";
    const result = await this.runCommand(command, [...args, fullPrompt], {      cwd,      env,      timeoutSec,      graceSec: config.graceSec || 20,      onStdout: (data) => {        fullText += data;
        onChunk(data);
      },    });
    if (result.timedOut) {      throw new Error(`Cursor timed out after ${timeoutSec}s`);
    }    if (result.exitCode !== 0 && !fullText) {      throw new Error(`Cursor exited with code ${result.exitCode}: ${result.stderr}`);
    }    return fullText;
  }  async testEnvironment(agent: Agent): Promise<AdapterEnvironmentTestResult> {    const checks: any[] = [];
    const config = this.parseConfig(agent);
    const command = config.command || "agent";
    const cliExists = await this.checkCommandExists(command);    checks.push({      code: "cli_exists",      level: cliExists ? "info" : "error",      message: cliExists        ? `Cursor agent CLI found: ${command}`        : `Cursor agent CLI not found: ${command}`,      hint: cliExists ? null : "Ensure Cursor IDE is installed and 'agent' is in PATH",    });
    if (!cliExists) {      return this.createTestResult(this.type, "fail", checks);
    }    const hasError = checks.some((c) => c.level === "error");
    return this.createTestResult(this.type, hasError ? "fail" : "pass", checks);
  }}