// Gemini CLI adapter — spawns Google Gemini CL
import { BaseAdapter } from "../base";
import { Agent, AdapterEnvironmentTestResult, AdapterConfig } from "../../types";
export class GeminiCliAdapter extends BaseAdapter {  type = "gemini_cli";
  label = "Gemini CLI";
  description = "Google Gemini CLI — experimental multi-modal agent";
  async isAvailable(agent: Agent): Promise<boolean> {    const config = this.parseConfig(agent);
    const command = config.command || "gemini";
    return this.checkCommandExists(command);
  }  async execute(agent: Agent, message: string, context?: string): Promise<string> {    const config = this.parseConfig(agent);
    const command = config.command || "gemini";
    const cwd = config.cwd || process.cwd();
    const model = config.model || "gemini-2.0-flash";
    const timeoutSec = config.timeoutSec || 300;
    const args = ["-m", model, "-p"];
    const env = this.buildEnv(agent, config, {      GEMINI_API_KEY: process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY || "",    });
    const fullPrompt = context      ? `[Context]\n${context}\n\n[Task]\n${message}`      : message;
    const result = await this.runCommand(command, [...args, fullPrompt], {      cwd,      env,      timeoutSec,      graceSec: config.graceSec || 20,    });
    if (result.timedOut) {      throw new Error(`Gemini CLI timed out after ${timeoutSec}s`);
    }    if (result.exitCode !== 0) {      throw new Error(`Gemini CLI exited with code ${result.exitCode}: ${result.stderr}`);
    }    return result.stdout.trim();
  }  async executeStreaming(    agent: Agent,    message: string,    context: string | undefined,    onChunk: (chunk: string) => void  ): Promise<string> {    const config = this.parseConfig(agent);
    const command = config.command || "gemini";
    const cwd = config.cwd || process.cwd();
    const model = config.model || "gemini-2.0-flash";
    const timeoutSec = config.timeoutSec || 300;
    const args = ["-m", model, "-p"];
    const env = this.buildEnv(agent, config, {      GEMINI_API_KEY: process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY || "",    });
    const fullPrompt = context      ? `[Context]\n${context}\n\n[Task]\n${message}`      : message;    let fullText = "";
    const result = await this.runCommand(command, [...args, fullPrompt], {      cwd,      env,      timeoutSec,      graceSec: config.graceSec || 20,      onStdout: (data) => {        fullText += data;
        onChunk(data);
      },    });
    if (result.timedOut) {      throw new Error(`Gemini CLI timed out after ${timeoutSec}s`);
    }    if (result.exitCode !== 0 && !fullText) {      throw new Error(`Gemini CLI exited with code ${result.exitCode}: ${result.stderr}`);
    }    return fullText;
  }  async testEnvironment(agent: Agent): Promise<AdapterEnvironmentTestResult> {    const checks: any[] = [];
    const config = this.parseConfig(agent);
    const command = config.command || "gemini";
    const cliExists = await this.checkCommandExists(command);    checks.push({      code: "cli_exists",      level: cliExists ? "info" : "error",      message: cliExists        ? `Gemini CLI found: ${command}`        : `Gemini CLI not found: ${command}`,      hint: cliExists ? null : "Install with: npm install -g @google/gemini-cli",    });
    if (!cliExists) {      return this.createTestResult(this.type, "fail", checks);
    }    const hasApiKey = !!(process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY);    checks.push({      code: "auth",      level: hasApiKey ? "info" : "error",      message: hasApiKey        ? "GEMINI_API_KEY / GOOGLE_API_KEY is set"        : "No API key found",      hint: hasApiKey ? null : "Set GEMINI_API_KEY or GOOGLE_API_KEY",    });
    const hasError = checks.some((c) => c.level === "error");
    return this.createTestResult(this.type, hasError ? "fail" : "pass", checks);
  }}