// Hermes adapter — spawns Hermes CL
import { BaseAdapter } from "../base";
import { Agent, AdapterEnvironmentTestResult, AdapterConfig } from "../../../shared/src/types";
export class HermesAdapter extends BaseAdapter {  type = "hermes";
  label = "Hermes";
  description = "Hermes AI Agent — custom agent runtime via Hermes CLI";
  async isAvailable(agent: Agent): Promise<boolean> {    const config = this.parseConfig(agent);
    const command = config.command || "hermes";
    return this.checkCommandExists(command);
  }  async execute(agent: Agent, message: string, context?: string): Promise<string> {    const config = this.parseConfig(agent);
    const command = config.command || "hermes";
    const cwd = config.cwd || process.cwd();
    const timeoutSec = config.timeoutSec || 300;
    const args = ["run"];
    if (config.model) args.push("--model", config.model);
    const env = this.buildEnv(agent, config, {      HERMES_RUN_ID: agent.id,    });
    const fullPrompt = context      ? `[Context]\n${context}\n\n[Task]\n${message}`      : message;
    const result = await this.runCommand(command, [...args, fullPrompt], {      cwd,      env,      timeoutSec,      graceSec: config.graceSec || 20,    });
    if (result.timedOut) {      throw new Error(`Hermes timed out after ${timeoutSec}s`);
    }    if (result.exitCode !== 0) {      throw new Error(`Hermes exited with code ${result.exitCode}: ${result.stderr}`);
    }    return result.stdout.trim();
  }  async executeStreaming(    agent: Agent,    message: string,    context: string | undefined,    onChunk: (chunk: string) => void  ): Promise<string> {    const config = this.parseConfig(agent);
    const command = config.command || "hermes";
    const cwd = config.cwd || process.cwd();
    const timeoutSec = config.timeoutSec || 300;
    const args = ["run"];
    if (config.model) args.push("--model", config.model);
    const env = this.buildEnv(agent, config, {      HERMES_RUN_ID: agent.id,    });
    const fullPrompt = context      ? `[Context]\n${context}\n\n[Task]\n${message}`      : message;    let fullText = "";
    const result = await this.runCommand(command, [...args, fullPrompt], {      cwd,      env,      timeoutSec,      graceSec: config.graceSec || 20,      onStdout: (data) => {        fullText += data;
        onChunk(data);
      },    });
    if (result.timedOut) {      throw new Error(`Hermes timed out after ${timeoutSec}s`);
    }    if (result.exitCode !== 0 && !fullText) {      throw new Error(`Hermes exited with code ${result.exitCode}: ${result.stderr}`);
    }    return fullText;
  }  async testEnvironment(agent: Agent): Promise<AdapterEnvironmentTestResult> {    const checks: any[] = [];
    const config = this.parseConfig(agent);
    const command = config.command || "hermes";
    const cliExists = await this.checkCommandExists(command);    checks.push({      code: "cli_exists",      level: cliExists ? "info" : "error",      message: cliExists        ? `Hermes CLI found: ${command}`        : `Hermes CLI not found: ${command}`,      hint: cliExists ? null : "Install Hermes CLI and ensure it's in PATH",    });
    if (!cliExists) {      return this.createTestResult(this.type, "fail", checks);
    }    const hasError = checks.some((c) => c.level === "error");
    return this.createTestResult(this.type, hasError ? "fail" : "pass", checks);
  }}