// OpenCode adapter — spawns OpenCode CL
import { BaseAdapter } from "../base";
import { Agent, AdapterEnvironmentTestResult, AdapterConfig } from "@nmj/shared/types";
export class OpenCodeAdapter extends BaseAdapter {  type = "opencode";
  label = "OpenCode";
  description = "OpenCode CLI — multi-provider coding agent";
  async isAvailable(agent: Agent): Promise<boolean> {    const config = this.parseConfig(agent);
    const command = config.command || "opencode";
    return this.checkCommandExists(command);
  }  async execute(agent: Agent, message: string, context?: string): Promise<string> {    const config = this.parseConfig(agent);
    const command = config.command || "opencode";
    const cwd = config.cwd || process.cwd();
    const model = config.model || "";
    const timeoutSec = config.timeoutSec || 600;
    const args = ["run"];
    if (model) args.push("-m", model);
    if (config.effort) args.push("--effort", config.effort);
    const env = this.buildEnv(agent, config);
    const fullPrompt = context      ? `[Context]\n${context}\n\n[Task]\n${message}`      : message;
    const result = await this.runCommand(command, [...args, fullPrompt], {      cwd,      env,      timeoutSec,      graceSec: config.graceSec || 20,    });
    if (result.timedOut) {      throw new Error(`OpenCode timed out after ${timeoutSec}s`);
    }    if (result.exitCode !== 0) {      throw new Error(`OpenCode exited with code ${result.exitCode}: ${result.stderr}`);
    }    return result.stdout.trim();
  }  async executeStreaming(    agent: Agent,    message: string,    context: string | undefined,    onChunk: (chunk: string) => void  ): Promise<string> {    const config = this.parseConfig(agent);
    const command = config.command || "opencode";
    const cwd = config.cwd || process.cwd();
    const model = config.model || "";
    const timeoutSec = config.timeoutSec || 600;
    const args = ["run"];
    if (model) args.push("-m", model);
    if (config.effort) args.push("--effort", config.effort);
    const env = this.buildEnv(agent, config);
    const fullPrompt = context      ? `[Context]\n${context}\n\n[Task]\n${message}`      : message;    let fullText = "";
    const result = await this.runCommand(command, [...args, fullPrompt], {      cwd,      env,      timeoutSec,      graceSec: config.graceSec || 20,      onStdout: (data) => {        fullText += data;
        onChunk(data);
      },    });
    if (result.timedOut) {      throw new Error(`OpenCode timed out after ${timeoutSec}s`);
    }    if (result.exitCode !== 0 && !fullText) {      throw new Error(`OpenCode exited with code ${result.exitCode}: ${result.stderr}`);
    }    return fullText;
  }  async testEnvironment(agent: Agent): Promise<AdapterEnvironmentTestResult> {    const checks: any[] = [];
    const config = this.parseConfig(agent);
    const command = config.command || "opencode";
    const cliExists = await this.checkCommandExists(command);    checks.push({      code: "cli_exists",      level: cliExists ? "info" : "error",      message: cliExists        ? `OpenCode CLI found: ${command}`        : `OpenCode CLI not found: ${command}`,      hint: cliExists ? null : "Install opencode-ai package",    });
    if (!cliExists) {      return this.createTestResult(this.type, "fail", checks);
    }    if (config.model) {      checks.push({        code: "model",        level: "info",        message: `Model: ${config.model}`,      });
    } else {      checks.push({        code: "model",        level: "warn",        message: "No model configured — will use OpenCode default",      });
    }    const hasError = checks.some((c) => c.level === "error");
    const hasWarn = checks.some((c) => c.level === "warn");
    return this.createTestResult(      this.type,      hasError ? "fail" : hasWarn ? "warn" : "pass",      checks    );
  }}