// HTTP adapter — sends webhooks to external agent service
import { BaseAdapter } from "../base";
import { Agent, AdapterEnvironmentTestResult, AdapterConfig } from "../../../shared/src/types";
export class HttpAdapter extends BaseAdapter {  type = "http";
  label = "HTTP Webhook";
  description = "Send requests to external agent services via HTTP webhooks";
  async isAvailable(agent: Agent): Promise<boolean> {    const config = this.parseConfig(agent);
    const url = config.url;
    if (!url) return false;
    try {      const res = await fetch(url, {        method: "HEAD",        signal: AbortSignal.timeout(5000),      });
      return res.ok || res.status < 500;
    } catch {      return false;
    }  }  async execute(agent: Agent, message: string, context?: string): Promise<string> {    const config = this.parseConfig(agent);
    const url = config.url;
    if (!url) throw new Error("HTTP adapter requires a 'url' in adapter config");
    const headers: Record<string, string> = {      "Content-Type": "application/json",      ...(config.headers || {}),    };
    if (config.authToken) {      headers["Authorization"] = `Bearer ${config.authToken}`;
    }    const payload: Record<string, unknown> = {      message: context        ? `[Context]\n${context}\n\n[Task]\n${message}`        : message,      agentId: agent.id,      agentName: agent.name,      agentRole: agent.role,    };
    const res = await fetch(url, {      method: "POST",      headers,      body: JSON.stringify(payload),      signal: AbortSignal.timeout((config.timeoutSec || 120) * 1000),    });
    if (!res.ok) {      const errText = await res.text();
      throw new Error(`HTTP adapter error ${res.status}: ${errText}`);
    }    let data: Record<string, unknown>;
    try {      data = await res.json() as Record<string, unknown>;
    } catch {      const rawText = await res.text();
      return rawText || "";
    }    return (data.response as string) || (data.content as string) || (data.result as string) || "";
  }  async executeStreaming(    agent: Agent,    message: string,    context: string | undefined,    onChunk: (chunk: string) => void  ): Promise<string> {    const config = this.parseConfig(agent);
    const url = config.url;
    if (!url) throw new Error("HTTP adapter requires a 'url' in adapter config");
    const headers: Record<string, string> = {      "Content-Type": "application/json",      ...(config.headers || {}),    };
    if (config.authToken) {      headers["Authorization"] = `Bearer ${config.authToken}`;
    }    const payload: Record<string, unknown> = {      message: context        ? `[Context]\n${context}\n\n[Task]\n${message}`        : message,      agentId: agent.id,      agentName: agent.name,      agentRole: agent.role,      stream: true,    };
    const res = await fetch(url, {      method: "POST",      headers,      body: JSON.stringify(payload),      signal: AbortSignal.timeout((config.timeoutSec || 120) * 1000),    });
    if (!res.ok) {      const errText = await res.text();
      throw new Error(`HTTP adapter error ${res.status}: ${errText}`);
    }    const reader = res.body?.getReader();
    if (!reader) throw new Error("No response body");
    const decoder = new TextDecoder();    let fullText = "";    let buffer = "";    while (true) {      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split("\n");
      buffer = lines.pop() || "";
      for (const line of lines) {        const trimmed = line.trim();
        if (!trimmed || !trimmed.startsWith("data: ")) continue;
        const data = trimmed.slice(6);
        if (data === "[DONE]") continue;
        try {          const parsed = JSON.parse(data);
          const delta = parsed.choices?.[0]?.delta?.content || parsed.delta || parsed.content;
          if (delta) {            fullText += delta;
            onChunk(delta);
          }        } catch { /* skip */ }      }    }    return fullText;
  }  async testEnvironment(agent: Agent): Promise<AdapterEnvironmentTestResult> {    const checks: any[] = [];
    const config = this.parseConfig(agent);
    const url = config.url || "";
    if (!url) {      checks.push({        code: "url_missing",        level: "error",        message: "URL is not configured",        hint: "Set 'url' in adapter config to the webhook endpoint",      });
      return this.createTestResult(this.type, "fail", checks);
    }    checks.push({      code: "url",      level: "info",      message: `Webhook URL: ${url}`,    });
    const reachable = await this.isAvailable(agent);    checks.push({      code: "reachable",      level: reachable ? "info" : "warn",      message: reachable        ? "Endpoint is reachable"        : "Endpoint is not reachable (may still work for POST requests)",    });
    if (config.authToken) {      checks.push({        code: "auth",        level: "info",        message: "Auth token is configured",      });
    }    const hasError = checks.some((c) => c.level === "error");
    return this.createTestResult(this.type, hasError ? "fail" : "pass", checks);
  }}